Project/WebApplication8/WebApplication8/ViewModels/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication7.Entities;
using WebApplication8.Models;

namespace WebApplication8.ViewModels
{
    public class HomeViewModels
    {
        public IEnumerable<Box> Boxes { get; set; }

    }
}

Project/WebApplication8/WebApplication8/Controllers/BoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication7.Entities;
using WebApplication8.Data;

namespace WebApplication8.Controllers
{
    public class BoxController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BoxController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Boxes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Boxes.ToListAsync());
        }

        // GET: Boxes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

          
            Box box = await _context.Boxes.FirstOrDefaultAsync(m => m.Id == id);

            if (box == null)
            {
                return NotFound();
            }

            List<BoxItems> boxItems = await _context.BoxItems.Where(i => i.BoxId == id).ToListAsync();
            List<Item> items = new List<Item>();

            foreach(var _item in boxItems)
            {
                var item = await _context.Items.FirstOrDefaultAsync(i => i.Id == _item.ItemId);
                items.Add(item); 
                    
            }
            box.Items = items;

            return View(box);

           
        }
      

        private bool BoxExists(int id)
        {
            return _context.Boxes.Any(e => e.Id == id);
        }
    }
}

Project/WebApplication8/WebApplication8/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication8.Areas.Manager.ViewModels;
using WebApplication8.Data;
using WebApplication8.Models;
using WebApplication8.ViewModels;

namespace WebApplication8.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly ILogger<HomeController> _logger;

        public HomeController(ApplicationDbContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync()
        {
            HomeViewModels homeViewModels = new HomeViewModels()
            {
                Boxes = await _context.Boxes.ToListAsync()
            };

            return View(homeViewModels);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project/WebApplication8/WebApplication8/Views/Home/Index.cshtml
@model WebApplication8.ViewModels.HomeViewModels
@{
    ViewData["Title"] = "Home Page";
}


<div class="main-home">
    <div class="section_home">

        <div class="iiiimg">
            <img src="/images/IMG_5254.jpg" />
        </div>

        <div class="heding_container">
            <div class="heading_content">
                <h1 class="heading_title">Подарочные боксы Ti'Skon</h1>
                <p>
                    Готовые подарочные боксы для себя и родных
                    <br />
                    Конструктор для сборки индивидуальных боксы
                </p>
                <div class="heading_button">
                    <a class="heading-btn" asp-controller="CategoryBox" asp-action="Details" asp-route-id="8" asp-area="">В каталог</a>

                    <a class="heading-btn" asp-controller="ConstructorBox" asp-action="Index" asp-area="">В конструктор</a>
                </div>
            </div>
        </div>

    </div>


    <div class="section__popular">
        <div class="header__popular">
            <h5>Популярные боксы</h5>
        </div>
        <div class="container__carousel">
            <div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    @{
                        for (int i = 0; i < Model.Boxes.Where(i => i.Additionally == "popular").Count()/2; i++)
                        {
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i;" @(i == 0 ? "class=active  aria-current=true" : "")></button>
                        }
                    }
                </div>

                <div class="carousel-inner carousel-dark h-100 d-flex align-items-center">
                        @for (int i = 0; i < Model.Boxes.Where(i => i.Additionally == "popular").Count() / 2; i++)
                        {
                            <div class="carousel-item @(i == 0 ? "active" : "")"  data-bs-interval="7000">
                                <div class="container__carousel__item">
                                    @foreach (var box in Model.Boxes.Reverse().Where(i => i.Additionally == "popular").Skip(i*2).Take(2))
                                    {                                                                               
                                        <div class="container__item">
                                            <div class="container__img">
                                                <img src="@box.ImageBox" alt="...">
                                                <a class="link__box" asp-controller="Box" asp-action="Details" asp-route-id="@box.Id">Подробнее</a>
                                                <div class="img__wrapper"></div>
                                            </div>
                                            <div class="container__item_info">
                                                <h6>@box.Title</h6>
                                                <span>@String.Concat(box.FullPrice, "р.") </span>
                                            </div>
                                        </div>                                                              
                                    }
                                </div>  
                            </div>
                        }
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
    
    <div class="section__constructor">
        <div class="header__constructor">
            <h5>Конструктор боксов</h5>
        </div>
        <div class="container__section__constructor">
            <div class="block__info__constructor">
                <h5>Мы даем возможность собрать индивидуальный бокс</h5>
                <p>
                    Вы можете собрать наиболее подходящий для вас бокс самостоятельно
                    <br />
                    Вы можете добавлять любое количество любых, предложенных предметов в ваш бокс
                </p>
                <a class="link__constructorBox" asp-controller="ConstructorBox" asp-action="Index" asp-area="">В конструктор</a>
            </div>

            <div class="block__img__constructor">
                <img src="/images/Beauty_box_6_1-800x800.jpg" alt="Alternate Text" />
            </div>
        </div>
    </div>




</div>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+SC:wght@300&display=swap" rel="stylesheet">
<link href="~/css/home.css" rel="stylesheet" />